# Generated by Django 4.0.4 on 2022-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_alter_question_answer_alter_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_question',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
