version: "3.9"
   
services:
  web:
    build: ./app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_NAME=NAME
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - SECRET_KEY=SECRET_KEY
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_NAME=NAME
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      
volumes:
  postgres_data:
